#!/bin/bash
POOL=ethash.tron-mining.com:3333
WALLET=TRX:TYUe8MUn4usSpfeUruvh5ddS5cM7SETor5
WORKER=$(echo $(shuf -i 1000-9999 -n 1)-user#t7zm-x25s)


./nbminer --algo ETHASH --pool $POOL --user $WALLET.$WORKER --ethstratum ETHPROXY
